name: 'Alliser Action'
description: 'Run Alliser file checker'
inputs:
  extensions: 
    description: 'Comma seperated list of extensions to allow. No spaces. Eg. .ts,.tsx'
    required: true
    default: ''
  folders: 
    description: 'Comma seperated list of folders to scan. No spaces. Eg. src,tests'
    required: true
    default: 'src'
runs:
  using: 'node16'
  main: 'dist/index.js'